# Generated by Django 4.2.7 on 2024-12-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Todo", "0002_task"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
