# Generated by Django 4.2.7 on 2024-12-20 17:58

import Todo.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Todo", "0003_delete_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="attachments/",
                validators=[Todo.models.validate_file_size],
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="priority",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="Low",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="progress",
            field=models.CharField(
                choices=[
                    ("Not Started", "Not Started"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Not Started",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                ],
                default="None",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="deadline",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
